services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  taxi_ingest:
    image: taxi_ingest:v001
    container_name: taxi_ingest
    stdin_open: true
    tty: true

volumes:
  ny_taxi_postgres_data: