[project]
name = "docker-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ZohaibR30", email = "zohaibrasool30@yahoo.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "pandas>=3.0.6",
    "pgcli>=4.7.1",
    "psycopg[binary,pool]>=3.3.6",
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.1.1",
    "tqdm>=4.70.1",
]

[project.scripts]
docker-workshop = "docker_workshop:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
